apiVersion: v1
kind: PersistentVolumeClaim # PersistentVolumeClaim 리소스 정의
metadata:
  name: host-pvc
spec:
  volumeName: host-pv # 바인딩할 PersistentVolume 이름(정적 바인딩)
  accessModes:
    - ReadWriteOnce # PV와 동일한 접근 모드(ReadWriteOnce) 요청
  storageClassName: standard # 매칭될 스토리지 클래스 이름
  resources:
    requests:
      storage: 1Gi # 요청할 최소 저장 용량
